### ISSUE TITLE
TMP117

### ISSUE THREAD

**Issue by anderswodenker** [breedwatch/monitoring-system#4]
TMP117 als Sensor mit aufnehmen

https://www.adafruit.com/product/4821

**Comment by 021631** [comment]
DHT22 kann stattdessen rausfliegen.. (siehe config.ini)

**Comment by anderswodenker** [comment]
Man kann entweder nur den AHT20 oder den TMP117 verwenden. In der data.csv ist an Stelle der AHT20 Temperatur dann die Temperatur des TMP117. Luftfeuchte ist dann 0.

Bitte beachten dass es vorher ein Update geben muss um das Paket zu installieren.

`sudo pip3 install adafruit-circuitpython-tmp117`

Die Zeile kann einfach mit in die update.sh eingefuegt werden.

Der Sensor steht ab Version 1.8 zur verfuegung.
