### ISSUE TITLE
data.csv konsistenz verbessern

### ISSUE THREAD

**Issue by anderswodenker** [breedwatch/monitoring-system#5]
data.csv immer die selbe anzahl an kommas, auch wenn keine daten geschrieben werden

**Comment by anderswodenker** [comment]
Die maximale Anzahl der DS18B20 wird auf zwei festgelegt. Ist ein Sensor nicht vorhanden, wird eine "0" für jeden fehlenden Sensor in der CSV eingetragen. Daher ergeben sich sieben Werte in der data.csv: 

time, device+location, hum, temp, weight, ds18b20-1, ds18b20-2

**Comment by 021631** [comment]
Es sollte ein "NA" für fehlende Sensoren eingetragen werden ODER eine leere Zelle (,,), aber auf keinen Fall eine "0". 
Bei den Werten fehlt der TMP117: 
time, device+location, hum, temp, weight, ds18b20-1, ds18b20-2, tmp117
